apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
    - name: http
      port: 3000          # service port in cluster
      targetPort: 3000    # container port
      nodePort: 31000     # VM/node port

